services:
  db:
    image: postgres:15
    container_name: app_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: app_api
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "
      uv run alembic upgrade head &&
      uv run uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

volumes:
  postgres_data: